<template>
  <div><el-card><template #header><div style="display:flex;justify-content:space-between;align-items:center"><span>客户档案</span><el-button type="primary" size="small" @click="openDialog()">新增客户</el-button></div></template>
      <el-row :gutter="12" style="margin-bottom:12px"><el-col :span="6"><el-input v-model="filters.keyword" placeholder="搜索姓名/手机号" @keyup.enter="fetchData"/></el-col><el-col :span="4"><el-select v-model="filters.customerType" placeholder="客户类型" clearable @change="fetchData"><el-option label="潜客" value="PROSPECT"/><el-option label="车主" value="OWNER"/></el-select></el-col><el-col :span="4"><el-select v-model="filters.grade" placeholder="客户级别" clearable @change="fetchData"><el-option v-for="g in ['H','A','B','C','D']" :key="g" :label="g+'级'" :value="g"/></el-select></el-col><el-col :span="4"><el-button type="primary" @click="fetchData">搜索</el-button></el-col></el-row>
      <el-table :data="tableData" border stripe v-loading="loading"><el-table-column prop="name" label="姓名"/><el-table-column prop="phone" label="手机号"/><el-table-column label="类型"><template #default="{row}"><el-tag>{{row.customerType==='PROSPECT'?'潜客':'车主'}}</el-tag></template></el-table-column><el-table-column prop="grade" label="级别" width="60"/><el-table-column prop="intentModel" label="意向车型"/><el-table-column prop="assigneeName" label="负责顾问"/><el-table-column label="操作" width="150"><template #default="{row}"><el-button size="small" @click="openDialog(row)">编辑</el-button><el-button size="small" type="danger" @click="del(row.id)">删除</el-button></template></el-table-column></el-table>
      <div style="margin-top:16px;text-align:right"><el-pagination v-model:current-page="page" :page-size="size" :total="total" layout="total,prev,pager,next" @current-change="fetchData"/></div></el-card>
    <el-dialog :title="form.id?'编辑客户':'新增客户'" v-model="dialogVisible" width="500px" @close="form={}"><el-form :model="form" label-width="80px"><el-form-item label="姓名"><el-input v-model="form.name"/></el-form-item><el-form-item label="手机号"><el-input v-model="form.phone"/></el-form-item><el-form-item label="客户类型"><el-select v-model="form.customerType"><el-option label="潜客" value="PROSPECT"/><el-option label="车主" value="OWNER"/></el-select></el-form-item><el-form-item label="级别"><el-select v-model="form.grade"><el-option v-for="g in ['H','A','B','C','D']" :key="g" :label="g+'级'" :value="g"/></el-select></el-form-item><el-form-item label="意向车型"><el-input v-model="form.intentModel"/></el-form-item><el-form-item label="预算"><el-input-number v-model="form.budget" :min="0" :step="10000" style="width:100%"/></el-form-item><el-form-item label="来源"><el-input v-model="form.source"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="saveForm">保存</el-button></template></el-dialog></div>
</template><script setup>
import { ref,onMounted } from 'vue';import api from '../../api';import { ElMessage } from 'element-plus'
const tableData=ref([]),loading=ref(false),page=ref(1),size=ref(10),total=ref(0),dialogVisible=ref(false),form=ref({}),filters=ref({keyword:'',customerType:'',grade:''})
async function fetchData(){loading.value=true;const res=await api.get('/api/crm/customers',{params:{page:page.value,size:size.value,...filters.value}});tableData.value=res.data.data.records;total.value=res.data.data.total;loading.value=false}
function openDialog(row){form.value=row?{...row}:{};dialogVisible.value=true}
async function saveForm(){if(form.value.id)await api.put(`/api/crm/customers/${form.value.id}`,form.value);else await api.post('/api/crm/customers',form.value);ElMessage.success('保存成功');dialogVisible.value=false;fetchData()}
async function del(id){await api.delete(`/api/crm/customers/${id}`);ElMessage.success('已删除');fetchData()}
onMounted(fetchData)
</script>
