<template>
  <div><el-card><template #header><div style="display:flex;justify-content:space-between"><span>线索公海</span><el-button type="primary" size="small" @click="openDialog()">新增线索</el-button></div></template>
      <el-row :gutter="12" style="margin-bottom:12px"><el-col :span="6"><el-select v-model="filters.status" placeholder="状态" clearable @change="fetchData"><el-option label="公海" value="PUBLIC"/><el-option label="已分配" value="ASSIGNED"/><el-option label="已转化" value="CONVERTED"/></el-select></el-col></el-row>
      <el-table :data="tableData" border stripe v-loading="loading"><el-table-column prop="customerName" label="客户名"/><el-table-column prop="phone" label="手机号"/><el-table-column prop="sourceChannel" label="来源渠道"/><el-table-column prop="intentModel" label="意向车型"/><el-table-column prop="status" label="状态"><template #default="{row}"><el-tag :type="row.status==='PUBLIC'?'info':row.status==='ASSIGNED'?'warning':'success'">{{row.status==='PUBLIC'?'公海':row.status==='ASSIGNED'?'已分配':'已转化'}}</el-tag></template></el-table-column><el-table-column label="操作" width="220"><template #default="{row}"><el-button size="small" @click="openDialog(row)">编辑</el-button><el-button v-if="row.status==='PUBLIC'" size="small" type="primary" @click="assignLead(row)">分配</el-button><el-button v-if="row.status==='ASSIGNED'" size="small" type="warning" @click="returnLead(row)">退回</el-button></template></el-table-column></el-table>
      <div style="margin-top:16px;text-align:right"><el-pagination v-model:current-page="page" :page-size="size" :total="total" layout="total,prev,pager,next" @current-change="fetchData"/></div></el-card>
    <el-dialog :title="form.id?'编辑线索':'新增线索'" v-model="dialogVisible" width="400px" @close="form={}"><el-form :model="form" label-width="80px"><el-form-item label="客户名"><el-input v-model="form.customerName"/></el-form-item><el-form-item label="手机号"><el-input v-model="form.phone"/></el-form-item><el-form-item label="来源"><el-input v-model="form.source"/></el-form-item><el-form-item label="意向车型"><el-input v-model="form.intentModel"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="saveForm">保存</el-button></template></el-dialog></div>
</template><script setup>
import { ref,onMounted } from 'vue';import api from '../../api';import { ElMessage,ElMessageBox } from 'element-plus'
const tableData=ref([]),loading=ref(false),page=ref(1),size=ref(10),total=ref(0),dialogVisible=ref(false),form=ref({}),filters=ref({status:''})
async function fetchData(){loading.value=true;const r=await api.get('/api/crm/leads',{params:{page:page.value,size:size.value,...filters.value}});tableData.value=r.data.data.records;total.value=r.data.data.total;loading.value=false}
function openDialog(row){form.value=row?{...row}:{};dialogVisible.value=true}
async function saveForm(){if(form.value.id)await api.put(`/api/crm/leads/${form.value.id}`,form.value);else await api.post('/api/crm/leads',form.value);ElMessage.success('OK');dialogVisible.value=false;fetchData()}
async function assignLead(row){const r=await ElMessageBox.prompt('输入分配顾问ID','分配线索');await api.post(`/api/crm/leads/${row.id}/assign`,{toUserId:parseInt(r.value),assignBy:1});ElMessage.success('已分配');fetchData()}
async function returnLead(row){await api.post(`/api/crm/leads/${row.id}/return`);ElMessage.success('已退回公海');fetchData()}
onMounted(fetchData)
</script>
