<template>
  <div><el-card><template #header><div style="display:flex;justify-content:space-between;align-items:center"><span>订单管理</span><el-button type="primary" size="small" @click="openDialog()">新建订单</el-button></div></template>
      <el-row :gutter="12" style="margin-bottom:12px"><el-col :span="6"><el-select v-model="filters.status" placeholder="订单状态" clearable @change="fetchData"><el-option label="待审批" value="PENDING_APPROVAL"/><el-option label="待交定金" value="PENDING_DEPOSIT"/><el-option label="待配车" value="PENDING_ALLOCATION"/><el-option label="待交车" value="PENDING_DELIVERY"/><el-option label="已完成" value="COMPLETED"/><el-option label="已取消" value="CANCELLED"/></el-select></el-col></el-row>
      <el-table :data="tableData" border stripe v-loading="loading"><el-table-column prop="orderNo" label="订单号" width="150"/><el-table-column prop="customerName" label="客户"/><el-table-column prop="guidePrice" label="指导价"/><el-table-column prop="discount" label="优惠"/><el-table-column prop="totalPrice" label="总价(万元)" :formatter="(r)=>r.totalPrice?r.totalPrice/10000:''"/><el-table-column prop="status" label="状态"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button size="small" @click="openDialog(row)">编辑</el-button><el-button v-if="row.status==='PENDING_APPROVAL'" size="small" type="success" @click="approve(row)">审批</el-button></template></el-table-column></el-table>
      <div style="margin-top:16px;text-align:right"><el-pagination v-model:current-page="page" :page-size="size" :total="total" layout="total,prev,pager,next" @current-change="fetchData"/></div></el-card>
    <el-dialog :title="form.id?'编辑订单':'新建订单'" v-model="dialogVisible" width="600px" @close="form={}"><el-form :model="form" label-width="100px"><el-form-item label="客户ID"><el-input-number v-model="form.customerId" style="width:100%"/></el-form-item><el-form-item label="车型ID"><el-input-number v-model="form.vehicleModelId" style="width:100%"/></el-form-item><el-form-item label="指导价"><el-input-number v-model="form.guidePrice" :min="0" :step="1000" style="width:100%"/></el-form-item><el-form-item label="优惠金额"><el-input-number v-model="form.discount" :min="0" :step="500" style="width:100%"/></el-form-item><el-form-item label="购置税"><el-input-number v-model="form.purchaseTax" :min="0" :step="100" style="width:100%"/></el-form-item><el-form-item label="保险费"><el-input-number v-model="form.insuranceAmount" :min="0" :step="100" style="width:100%"/></el-form-item><el-form-item label="上牌费"><el-input-number v-model="form.licenseFee" :min="0" :step="50" style="width:100%"/></el-form-item><el-form-item label="付款方式"><el-select v-model="form.paymentMethod"><el-option label="全款" value="FULL"/><el-option label="贷款" value="LOAN"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="saveForm">保存</el-button></template></el-dialog></div>
</template><script setup>
import { ref,onMounted } from 'vue';import api from '../../api';import { ElMessage } from 'element-plus'
const tableData=ref([]),loading=ref(false),page=ref(1),size=ref(10),total=ref(0),dialogVisible=ref(false),form=ref({}),filters=ref({status:''})
const sm={PENDING_APPROVAL:'待审批',PENDING_DEPOSIT:'待交定金',PENDING_ALLOCATION:'待配车',PENDING_DELIVERY:'待交车',COMPLETED:'已完成',CANCELLED:'已取消'}
const sc={PENDING_APPROVAL:'warning',PENDING_DEPOSIT:'info',PENDING_ALLOCATION:'',PENDING_DELIVERY:'',COMPLETED:'success',CANCELLED:'danger'}
function statusLabel(s){return sm[s]||s}
function statusType(s){return sc[s]||''}
async function fetchData(){loading.value=true;const res=await api.get('/api/sale/orders',{params:{page:page.value,size:size.value,...filters.value}});tableData.value=res.data.data.records;total.value=res.data.data.total;loading.value=false}
function openDialog(row){form.value=row?{...row}:{};dialogVisible.value=true}
async function saveForm(){if(form.value.id)await api.put(`/api/sale/orders/${form.value.id}`,form.value);else await api.post('/api/sale/orders',form.value);ElMessage.success('保存成功');dialogVisible.value=false;fetchData()}
async function approve(row){await api.post(`/api/sale/orders/${row.id}/approve`,{approverId:1,level:'MANAGER',approved:true,comment:'审批通过'});ElMessage.success('已审批');fetchData()}
onMounted(fetchData)
</script>
