<template>
  <div><el-card><template #header><div style="display:flex;justify-content:space-between"><span>整车库存</span><el-button type="primary" size="small" @click="openDialog()">录入车辆</el-button></div></template>
      <el-row :gutter="12" style="margin-bottom:12px"><el-col :span="6"><el-input v-model="filters.keyword" placeholder="搜索VIN/品牌/车型" @keyup.enter="fetchData"/></el-col><el-col :span="6"><el-select v-model="filters.status" placeholder="状态" clearable @change="fetchData"><el-option label="在库" value="IN_STOCK"/><el-option label="展厅" value="SHOWROOM"/><el-option label="已预订" value="RESERVED"/><el-option label="已交车" value="DELIVERED"/></el-select></el-col></el-row>
      <el-table :data="tableData" border stripe v-loading="loading"><el-table-column prop="vin" label="VIN码" width="160"/><el-table-column prop="brand" label="品牌"/><el-table-column prop="model" label="车型"/><el-table-column prop="color" label="颜色"/><el-table-column prop="guidePrice" label="指导价"/><el-table-column prop="status" label="状态"><template #default="{row}"><el-tag>{{{IN_STOCK:'在库',SHOWROOM:'展厅',RESERVED:'已预订',IN_TRANSIT:'在途',DELIVERED:'已交车'}[row.status]}}</el-tag></template></el-table-column><el-table-column label="库龄(天)" width="80"><template #default="{row}">{{row.inboundDate?Math.floor((Date.now()-new Date(row.inboundDate))/(86400000)):''}}</template></el-table-column><el-table-column label="操作" width="160" fixed="right"><template #default="{row}"><el-button type="primary" size="small" link @click="openDialog(row)">编辑</el-button><el-button type="success" size="small" link @click="openVideoDialog(row)">视频</el-button></template></el-table-column></el-table>
      <div style="margin-top:16px;text-align:right"><el-pagination v-model:current-page="page" :page-size="size" :total="total" layout="total,prev,pager,next" @current-change="fetchData"/></div></el-card>
    <el-dialog :title="form.id?'编辑车辆':'录入车辆'" v-model="dialogVisible" width="500px" @close="form={}"><el-form :model="form" label-width="80px"><el-form-item label="VIN码"><el-input v-model="form.vin"/></el-form-item><el-form-item label="品牌"><el-input v-model="form.brand"/></el-form-item><el-form-item label="车型"><el-input v-model="form.model"/></el-form-item><el-form-item label="年款"><el-input-number v-model="form.modelYear" :min="2010" :max="2026" style="width:100%"/></el-form-item><el-form-item label="车辆类型"><el-select v-model="form.vehicleType" style="width:100%"><el-option label="轿车" value="SEDAN"/><el-option label="SUV" value="SUV"/><el-option label="MPV" value="MPV"/><el-option label="跑车" value="SPORTS"/><el-option label="皮卡" value="PICKUP"/></el-select></el-form-item><el-form-item label="颜色"><el-input v-model="form.color"/></el-form-item><el-form-item label="指导价"><el-input-number v-model="form.guidePrice" :min="0" :step="10000" style="width:100%"/></el-form-item><el-form-item label="图片链接"><el-input v-model="form.imageUrl" placeholder="输入图片URL或上传本地文件"/></el-form-item><el-form-item label="本地上传"><el-upload :http-request="customUpload" :show-file-list="false" :before-upload="beforeUpload" accept="image/*"><el-button size="small">选择图片上传</el-button></el-upload></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="saveForm">保存</el-button></template></el-dialog>
    <el-dialog :title="'视频管理 - '+currentVehicle.brand+' '+currentVehicle.model" v-model="videoDialogVisible" width="600px" @close="videoList=[]"><div style="margin-bottom:16px;display:flex;gap:10px"><el-input v-model="newVideo.title" placeholder="视频标题" style="width:200px"/><el-input v-model="newVideo.videoUrl" placeholder="视频链接URL" style="flex:1"/><el-button type="primary" @click="addVideoLink">添加链接</el-button></div><el-divider content-position="left">本地上传</el-divider><div style="margin-bottom:16px"><el-upload :http-request="uploadVideo" :show-file-list="false" :before-upload="beforeVideoUpload" accept="video/*"><el-button>选择视频文件上传</el-button></el-upload></div><el-divider content-position="left">视频列表 ({{videoList.length}})</el-divider><el-table :data="videoList" border size="small"><el-table-column prop="title" label="标题"/><el-table-column prop="sourceType" label="来源" width="70"><template #default="{row}"><el-tag size="small" :type="row.sourceType==='LOCAL'?'success':''">{{row.sourceType==='LOCAL'?'本地':'链接'}}</el-tag></template></el-table-column><el-table-column label="预览" width="80"><template #default="{row}"><el-button size="small" link @click="previewVideo(row)">播放</el-button></template></el-table-column><el-table-column label="操作" width="80"><template #default="{row}"><el-button type="danger" size="small" link @click="deleteVideo(row.id)">删除</el-button></template></el-table-column></el-table></el-dialog>
    <el-dialog v-model="videoPreviewVisible" title="视频预览" width="700px"><iframe v-if="previewUrl&&isBili(previewUrl)" :src="biliEmbed(previewUrl)" allowfullscreen style="width:100%;height:420px;border:none"></iframe><video v-else-if="previewUrl" :src="previewUrl" controls autoplay style="width:100%;max-height:450px"></video></el-dialog></div>
</template><script setup>
import { ref,onMounted } from 'vue';import api from '../../api';import { ElMessage } from 'element-plus'
const tableData=ref([]),loading=ref(false),page=ref(1),size=ref(10),total=ref(0),dialogVisible=ref(false),form=ref({}),filters=ref({keyword:'',status:''})
const uploadUrl = '/api/stock/vehicles/upload'
const videoDialogVisible=ref(false),currentVehicle=ref({}),videoList=ref([]),newVideo=ref({title:'',videoUrl:''}),videoPreviewVisible=ref(false),previewUrl=ref('')
async function customUpload(options) {
  const fd = new FormData()
  fd.append('file', options.file)
  const res = await api.post(uploadUrl, fd)
  form.value.imageUrl = res.data.data
  ElMessage.success('上传成功')
}
function onUploadSuccess(res) { form.value.imageUrl = res.data; ElMessage.success('上传成功') }
function beforeUpload(file) { const ok = file.size < 5 * 1024 * 1024; if (!ok) ElMessage.error('图片不能超过5MB'); return ok }
async function fetchData(){loading.value=true;const r=await api.get('/api/stock/vehicles',{params:{page:page.value,size:size.value,...filters.value}});tableData.value=r.data.data.records;total.value=r.data.data.total;loading.value=false}
function openDialog(row){form.value=row?{...row}:{};dialogVisible.value=true}
async function saveForm(){if(form.value.id)await api.put(`/api/stock/vehicles/${form.value.id}`,form.value);else await api.post('/api/stock/vehicles',form.value);ElMessage.success('OK');dialogVisible.value=false;fetchData()}
async function openVideoDialog(row){currentVehicle.value=row;try{const r=await api.get(`/api/stock/vehicles/${row.id}/videos`);videoList.value=r.data.data||[]}catch(e){videoList.value=[]};videoDialogVisible.value=true}
async function addVideoLink(){if(!newVideo.value.videoUrl){ElMessage.warning('请输入视频链接');return}; await api.post(`/api/stock/vehicles/${currentVehicle.value.id}/videos`,{title:newVideo.value.title||'车辆视频',videoUrl:newVideo.value.videoUrl});ElMessage.success('添加成功');newVideo.value={title:'',videoUrl:''};openVideoDialog(currentVehicle.value)}
async function uploadVideo(options){const fd=new FormData();fd.append('file',options.file);const r=await api.post(`/api/stock/vehicles/${currentVehicle.value.id}/videos/upload`,fd);ElMessage.success('上传成功');openVideoDialog(currentVehicle.value)}
function beforeVideoUpload(file){const ok=file.size<100*1024*1024;if(!ok)ElMessage.error('视频不能超过100MB');return ok}
function previewVideo(row){previewUrl.value=row.videoUrl;videoPreviewVisible.value=true}
function isBili(url){return url.includes('bilibili.com')}
function biliEmbed(url){const m=url.match(/BV\w+/);return m?'//player.bilibili.com/player.html?bvid='+m[0]+'&high_quality=1&autoplay=1':url}
async function deleteVideo(id){await api.delete(`/api/stock/vehicles/${currentVehicle.value.id}/videos/`+id);ElMessage.success('已删除');openVideoDialog(currentVehicle.value)}
onMounted(fetchData)
</script>
